### ISSUE TITLE
Wiki Quick-start Instructions are incorrect / misleading

### ISSUE THREAD

**Issue by danryu** [nebula-plugins/nebula-docker-plugin#26]
The wiki quick-start instructions do not work.

At https://github.com/nebula-plugins/nebula-docker-plugin/wiki 
the instructions say to add this to build.gradle:

```
buildscript {
    repositories { jcenter() }
    dependencies {
        classpath "com.netflix.nebula:nebula-docker-plugin:latest.release"
    }
}
apply plugin: 'nebula.docker'
```

However gradle fails to run with this configuration, with the following error:
`> Could not get unknown property 'applicationName' for root project 'someProject' of type org.gradle.api.Project.`

To reproduce, simply create a "build.gradle" with the above configuration, and run the command "gradle" in the same directory.

To correct the failure, I have to add plugin "application" explicitly to build.gradle:
```
buildscript {
    repositories { jcenter() }
    dependencies {
        classpath "com.netflix.nebula:nebula-docker-plugin:latest.release"
    }
}
apply plugin: 'nebula.docker'
apply plugin: 'application'
```

and then "gradle" executes correctly.

If I understand correctly, "application" should be pulled in as an implicit dependency.
Can you help me understand what's wrong here?

**Comment by liviutudor** [comment]
Hi @danryu , to clarify : the plugin helps in building a docker image. While the plugin is a bit opinionated (in the spirit of `nebula`), this particular opinion makes sense: you only build docker images for java applications, that is for a java package which you can run from the command line. As such there has to be a "main" class with a `public static void main(String[]args)` method -- which is the same as saying a java application. 
While it is true that you can meet all those conditions without using the gradle `application` plugin, this plugin is of the opinion that you should use the application plugin in order to use this.
As such in terms of code there is nothing that I need to fix and the plugin does exactly what is expected to do. However, you do have a point about the fact that the wiki should make it clear that is the case and that it expects the `application` plugin applied, so I will update the wiki to reflect this.
Thank you for signaling this!

**Comment by liviutudor** [comment]
@danryu I have updated the wiki. The wiki stated from the beginning that the plugin _relies_ on the `application` plugin but I guess it never explained the implications of that. Hopefully the recent updates solve that confusion.
